steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t', 'gcr.io/$PROJECT_ID/camp-image:$COMMIT_SHA','.']

  - name: 'gcr.io/cloud-builders/docker'
    ['push','gcr.io/$PROJECT_ID/camp-image:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run','deploy', 'camp-service',
      '--image', 'gcr.io/$PROJECT_ID/camp-image:$COMMIT_SHA',
      '--region', 'us-east4',
      '--allow-unauthenticated',
      '--set-traffic', 'latest=100'
    ]
    
serviceAccount: camp-477922@appspot.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
