steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-image:$COMMIT_SHA', '-f', 'frontend/Dockerfile.frontend', 'frontend']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend-image:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'camp-service',
    '--image', 'gcr.io/$PROJECT_ID/frontend-image:$COMMIT_SHA',
    '--region', 'us-east4',
    '--allow-unauthenticated',
    '--service-account', 'camp-477922@appspot.gserviceaccount.com'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-image:$COMMIT_SHA', '-f', 'backend/Dockerfile.backend', 'backend']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend-image:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'camp-service',
    '--image', 'gcr.io/$PROJECT_ID/backend-image:$COMMIT_SHA',
    '--region', 'us-east4',
    '--allow-unauthenticated',
    '--service-account', 'camp-477922@appspot.gserviceaccount.com',
    '--cpu', '4',
    '--memory', '16Gi',
    '--timeout', '300',
    '--cpu-boost',
    '--min-instances', '1',
    '--max-instances', '5',
    '--concurrency', '5',
    '--cpu-throttling',
    '--set-env-vars', 'GCS_BUCKET_NAME=crime-dataset-bucket'
  ]

serviceAccount: camp-477922@appspot.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY



