FROM python:3.11-slim
RUN apt-get update && apt-get install -y \
    build-essential \
    gdal-bin \
    libgdal-dev \
    libgeos-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
COPY backend/sample_df_50k.csv /app/sample_df_50k.csv
COPY backend/nyc_nta_2020.geojson /app/nyc_nta_2020.geojson
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PORT=8080
CMD gunicorn -b 0.0.0.0:8080 main:app